/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.2.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelAgentPluginsStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAgentPluginsStatus{}

// ModelAgentPluginsStatus struct for ModelAgentPluginsStatus
type ModelAgentPluginsStatus struct {
	FilesystemTracerStatus ModelPluginStatus `json:"filesystem_tracer_status"`
	NetworkFilterStatus ModelPluginStatus `json:"network_filter_status"`
	NetworkTracerStatus ModelPluginStatus `json:"network_tracer_status"`
	ProcessTracerStatus ModelPluginStatus `json:"process_tracer_status"`
}

type _ModelAgentPluginsStatus ModelAgentPluginsStatus

// NewModelAgentPluginsStatus instantiates a new ModelAgentPluginsStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAgentPluginsStatus(filesystemTracerStatus ModelPluginStatus, networkFilterStatus ModelPluginStatus, networkTracerStatus ModelPluginStatus, processTracerStatus ModelPluginStatus) *ModelAgentPluginsStatus {
	this := ModelAgentPluginsStatus{}
	this.FilesystemTracerStatus = filesystemTracerStatus
	this.NetworkFilterStatus = networkFilterStatus
	this.NetworkTracerStatus = networkTracerStatus
	this.ProcessTracerStatus = processTracerStatus
	return &this
}

// NewModelAgentPluginsStatusWithDefaults instantiates a new ModelAgentPluginsStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAgentPluginsStatusWithDefaults() *ModelAgentPluginsStatus {
	this := ModelAgentPluginsStatus{}
	return &this
}

// GetFilesystemTracerStatus returns the FilesystemTracerStatus field value
func (o *ModelAgentPluginsStatus) GetFilesystemTracerStatus() ModelPluginStatus {
	if o == nil {
		var ret ModelPluginStatus
		return ret
	}

	return o.FilesystemTracerStatus
}

// GetFilesystemTracerStatusOk returns a tuple with the FilesystemTracerStatus field value
// and a boolean to check if the value has been set.
func (o *ModelAgentPluginsStatus) GetFilesystemTracerStatusOk() (*ModelPluginStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilesystemTracerStatus, true
}

// SetFilesystemTracerStatus sets field value
func (o *ModelAgentPluginsStatus) SetFilesystemTracerStatus(v ModelPluginStatus) {
	o.FilesystemTracerStatus = v
}

// GetNetworkFilterStatus returns the NetworkFilterStatus field value
func (o *ModelAgentPluginsStatus) GetNetworkFilterStatus() ModelPluginStatus {
	if o == nil {
		var ret ModelPluginStatus
		return ret
	}

	return o.NetworkFilterStatus
}

// GetNetworkFilterStatusOk returns a tuple with the NetworkFilterStatus field value
// and a boolean to check if the value has been set.
func (o *ModelAgentPluginsStatus) GetNetworkFilterStatusOk() (*ModelPluginStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkFilterStatus, true
}

// SetNetworkFilterStatus sets field value
func (o *ModelAgentPluginsStatus) SetNetworkFilterStatus(v ModelPluginStatus) {
	o.NetworkFilterStatus = v
}

// GetNetworkTracerStatus returns the NetworkTracerStatus field value
func (o *ModelAgentPluginsStatus) GetNetworkTracerStatus() ModelPluginStatus {
	if o == nil {
		var ret ModelPluginStatus
		return ret
	}

	return o.NetworkTracerStatus
}

// GetNetworkTracerStatusOk returns a tuple with the NetworkTracerStatus field value
// and a boolean to check if the value has been set.
func (o *ModelAgentPluginsStatus) GetNetworkTracerStatusOk() (*ModelPluginStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkTracerStatus, true
}

// SetNetworkTracerStatus sets field value
func (o *ModelAgentPluginsStatus) SetNetworkTracerStatus(v ModelPluginStatus) {
	o.NetworkTracerStatus = v
}

// GetProcessTracerStatus returns the ProcessTracerStatus field value
func (o *ModelAgentPluginsStatus) GetProcessTracerStatus() ModelPluginStatus {
	if o == nil {
		var ret ModelPluginStatus
		return ret
	}

	return o.ProcessTracerStatus
}

// GetProcessTracerStatusOk returns a tuple with the ProcessTracerStatus field value
// and a boolean to check if the value has been set.
func (o *ModelAgentPluginsStatus) GetProcessTracerStatusOk() (*ModelPluginStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessTracerStatus, true
}

// SetProcessTracerStatus sets field value
func (o *ModelAgentPluginsStatus) SetProcessTracerStatus(v ModelPluginStatus) {
	o.ProcessTracerStatus = v
}

func (o ModelAgentPluginsStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAgentPluginsStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filesystem_tracer_status"] = o.FilesystemTracerStatus
	toSerialize["network_filter_status"] = o.NetworkFilterStatus
	toSerialize["network_tracer_status"] = o.NetworkTracerStatus
	toSerialize["process_tracer_status"] = o.ProcessTracerStatus
	return toSerialize, nil
}

func (o *ModelAgentPluginsStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filesystem_tracer_status",
		"network_filter_status",
		"network_tracer_status",
		"process_tracer_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelAgentPluginsStatus := _ModelAgentPluginsStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelAgentPluginsStatus)

	if err != nil {
		return err
	}

	*o = ModelAgentPluginsStatus(varModelAgentPluginsStatus)

	return err
}

type NullableModelAgentPluginsStatus struct {
	value *ModelAgentPluginsStatus
	isSet bool
}

func (v NullableModelAgentPluginsStatus) Get() *ModelAgentPluginsStatus {
	return v.value
}

func (v *NullableModelAgentPluginsStatus) Set(val *ModelAgentPluginsStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAgentPluginsStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAgentPluginsStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAgentPluginsStatus(val *ModelAgentPluginsStatus) *NullableModelAgentPluginsStatus {
	return &NullableModelAgentPluginsStatus{value: val, isSet: true}
}

func (v NullableModelAgentPluginsStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAgentPluginsStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


