/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v2.5.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ControlsQuarantineConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlsQuarantineConfig{}

// ControlsQuarantineConfig struct for ControlsQuarantineConfig
type ControlsQuarantineConfig struct {
	NodeId string `json:"node_id"`
	Policies []ControlsRuncPolicy `json:"policies"`
	UpdatedAt int32 `json:"updated_at"`
}

type _ControlsQuarantineConfig ControlsQuarantineConfig

// NewControlsQuarantineConfig instantiates a new ControlsQuarantineConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlsQuarantineConfig(nodeId string, policies []ControlsRuncPolicy, updatedAt int32) *ControlsQuarantineConfig {
	this := ControlsQuarantineConfig{}
	this.NodeId = nodeId
	this.Policies = policies
	this.UpdatedAt = updatedAt
	return &this
}

// NewControlsQuarantineConfigWithDefaults instantiates a new ControlsQuarantineConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlsQuarantineConfigWithDefaults() *ControlsQuarantineConfig {
	this := ControlsQuarantineConfig{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *ControlsQuarantineConfig) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ControlsQuarantineConfig) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ControlsQuarantineConfig) SetNodeId(v string) {
	o.NodeId = v
}

// GetPolicies returns the Policies field value
// If the value is explicit nil, the zero value for []ControlsRuncPolicy will be returned
func (o *ControlsQuarantineConfig) GetPolicies() []ControlsRuncPolicy {
	if o == nil {
		var ret []ControlsRuncPolicy
		return ret
	}

	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ControlsQuarantineConfig) GetPoliciesOk() ([]ControlsRuncPolicy, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// SetPolicies sets field value
func (o *ControlsQuarantineConfig) SetPolicies(v []ControlsRuncPolicy) {
	o.Policies = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ControlsQuarantineConfig) GetUpdatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ControlsQuarantineConfig) GetUpdatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ControlsQuarantineConfig) SetUpdatedAt(v int32) {
	o.UpdatedAt = v
}

func (o ControlsQuarantineConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlsQuarantineConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node_id"] = o.NodeId
	if o.Policies != nil {
		toSerialize["policies"] = o.Policies
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ControlsQuarantineConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
		"policies",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varControlsQuarantineConfig := _ControlsQuarantineConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varControlsQuarantineConfig)

	if err != nil {
		return err
	}

	*o = ControlsQuarantineConfig(varControlsQuarantineConfig)

	return err
}

type NullableControlsQuarantineConfig struct {
	value *ControlsQuarantineConfig
	isSet bool
}

func (v NullableControlsQuarantineConfig) Get() *ControlsQuarantineConfig {
	return v.value
}

func (v *NullableControlsQuarantineConfig) Set(val *ControlsQuarantineConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableControlsQuarantineConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableControlsQuarantineConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlsQuarantineConfig(val *ControlsQuarantineConfig) *NullableControlsQuarantineConfig {
	return &NullableControlsQuarantineConfig{value: val, isSet: true}
}

func (v NullableControlsQuarantineConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlsQuarantineConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


