/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelAlertsActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAlertsActionRequest{}

// ModelAlertsActionRequest struct for ModelAlertsActionRequest
type ModelAlertsActionRequest struct {
	NodeIds []string `json:"node_ids"`
}

type _ModelAlertsActionRequest ModelAlertsActionRequest

// NewModelAlertsActionRequest instantiates a new ModelAlertsActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAlertsActionRequest(nodeIds []string) *ModelAlertsActionRequest {
	this := ModelAlertsActionRequest{}
	this.NodeIds = nodeIds
	return &this
}

// NewModelAlertsActionRequestWithDefaults instantiates a new ModelAlertsActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAlertsActionRequestWithDefaults() *ModelAlertsActionRequest {
	this := ModelAlertsActionRequest{}
	return &this
}

// GetNodeIds returns the NodeIds field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ModelAlertsActionRequest) GetNodeIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.NodeIds
}

// GetNodeIdsOk returns a tuple with the NodeIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelAlertsActionRequest) GetNodeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.NodeIds) {
		return nil, false
	}
	return o.NodeIds, true
}

// SetNodeIds sets field value
func (o *ModelAlertsActionRequest) SetNodeIds(v []string) {
	o.NodeIds = v
}

func (o ModelAlertsActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAlertsActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NodeIds != nil {
		toSerialize["node_ids"] = o.NodeIds
	}
	return toSerialize, nil
}

func (o *ModelAlertsActionRequest) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelAlertsActionRequest := _ModelAlertsActionRequest{}

	err = json.Unmarshal(bytes, &varModelAlertsActionRequest)

	if err != nil {
		return err
	}

	*o = ModelAlertsActionRequest(varModelAlertsActionRequest)

	return err
}

type NullableModelAlertsActionRequest struct {
	value *ModelAlertsActionRequest
	isSet bool
}

func (v NullableModelAlertsActionRequest) Get() *ModelAlertsActionRequest {
	return v.value
}

func (v *NullableModelAlertsActionRequest) Set(val *ModelAlertsActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAlertsActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAlertsActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAlertsActionRequest(val *ModelAlertsActionRequest) *NullableModelAlertsActionRequest {
	return &NullableModelAlertsActionRequest{value: val, isSet: true}
}

func (v NullableModelAlertsActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAlertsActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


