/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v3.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ControlsThreatIntelInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlsThreatIntelInfo{}

// ControlsThreatIntelInfo struct for ControlsThreatIntelInfo
type ControlsThreatIntelInfo struct {
	CloudPostureControlsHash string `json:"cloud_posture_controls_hash"`
	CloudPostureControlsUrl string `json:"cloud_posture_controls_url"`
	IgnoredAlertRuleIds []string `json:"ignored_alert_rule_ids"`
	InternalIps []string `json:"internal_ips"`
	MalwareScannerRulesHash string `json:"malware_scanner_rules_hash"`
	MalwareScannerRulesUrl string `json:"malware_scanner_rules_url"`
	NetworkAlertRulesUrl string `json:"network_alert_rules_url"`
	RulesHash string `json:"rules_hash"`
	SecretScannerRulesHash string `json:"secret_scanner_rules_hash"`
	SecretScannerRulesUrl string `json:"secret_scanner_rules_url"`
	UpdatedAt int32 `json:"updated_at"`
}

type _ControlsThreatIntelInfo ControlsThreatIntelInfo

// NewControlsThreatIntelInfo instantiates a new ControlsThreatIntelInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlsThreatIntelInfo(cloudPostureControlsHash string, cloudPostureControlsUrl string, ignoredAlertRuleIds []string, internalIps []string, malwareScannerRulesHash string, malwareScannerRulesUrl string, networkAlertRulesUrl string, rulesHash string, secretScannerRulesHash string, secretScannerRulesUrl string, updatedAt int32) *ControlsThreatIntelInfo {
	this := ControlsThreatIntelInfo{}
	this.CloudPostureControlsHash = cloudPostureControlsHash
	this.CloudPostureControlsUrl = cloudPostureControlsUrl
	this.IgnoredAlertRuleIds = ignoredAlertRuleIds
	this.InternalIps = internalIps
	this.MalwareScannerRulesHash = malwareScannerRulesHash
	this.MalwareScannerRulesUrl = malwareScannerRulesUrl
	this.NetworkAlertRulesUrl = networkAlertRulesUrl
	this.RulesHash = rulesHash
	this.SecretScannerRulesHash = secretScannerRulesHash
	this.SecretScannerRulesUrl = secretScannerRulesUrl
	this.UpdatedAt = updatedAt
	return &this
}

// NewControlsThreatIntelInfoWithDefaults instantiates a new ControlsThreatIntelInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlsThreatIntelInfoWithDefaults() *ControlsThreatIntelInfo {
	this := ControlsThreatIntelInfo{}
	return &this
}

// GetCloudPostureControlsHash returns the CloudPostureControlsHash field value
func (o *ControlsThreatIntelInfo) GetCloudPostureControlsHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudPostureControlsHash
}

// GetCloudPostureControlsHashOk returns a tuple with the CloudPostureControlsHash field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetCloudPostureControlsHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudPostureControlsHash, true
}

// SetCloudPostureControlsHash sets field value
func (o *ControlsThreatIntelInfo) SetCloudPostureControlsHash(v string) {
	o.CloudPostureControlsHash = v
}

// GetCloudPostureControlsUrl returns the CloudPostureControlsUrl field value
func (o *ControlsThreatIntelInfo) GetCloudPostureControlsUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudPostureControlsUrl
}

// GetCloudPostureControlsUrlOk returns a tuple with the CloudPostureControlsUrl field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetCloudPostureControlsUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudPostureControlsUrl, true
}

// SetCloudPostureControlsUrl sets field value
func (o *ControlsThreatIntelInfo) SetCloudPostureControlsUrl(v string) {
	o.CloudPostureControlsUrl = v
}

// GetIgnoredAlertRuleIds returns the IgnoredAlertRuleIds field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ControlsThreatIntelInfo) GetIgnoredAlertRuleIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.IgnoredAlertRuleIds
}

// GetIgnoredAlertRuleIdsOk returns a tuple with the IgnoredAlertRuleIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ControlsThreatIntelInfo) GetIgnoredAlertRuleIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.IgnoredAlertRuleIds) {
		return nil, false
	}
	return o.IgnoredAlertRuleIds, true
}

// SetIgnoredAlertRuleIds sets field value
func (o *ControlsThreatIntelInfo) SetIgnoredAlertRuleIds(v []string) {
	o.IgnoredAlertRuleIds = v
}

// GetInternalIps returns the InternalIps field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ControlsThreatIntelInfo) GetInternalIps() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.InternalIps
}

// GetInternalIpsOk returns a tuple with the InternalIps field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ControlsThreatIntelInfo) GetInternalIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.InternalIps) {
		return nil, false
	}
	return o.InternalIps, true
}

// SetInternalIps sets field value
func (o *ControlsThreatIntelInfo) SetInternalIps(v []string) {
	o.InternalIps = v
}

// GetMalwareScannerRulesHash returns the MalwareScannerRulesHash field value
func (o *ControlsThreatIntelInfo) GetMalwareScannerRulesHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MalwareScannerRulesHash
}

// GetMalwareScannerRulesHashOk returns a tuple with the MalwareScannerRulesHash field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetMalwareScannerRulesHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MalwareScannerRulesHash, true
}

// SetMalwareScannerRulesHash sets field value
func (o *ControlsThreatIntelInfo) SetMalwareScannerRulesHash(v string) {
	o.MalwareScannerRulesHash = v
}

// GetMalwareScannerRulesUrl returns the MalwareScannerRulesUrl field value
func (o *ControlsThreatIntelInfo) GetMalwareScannerRulesUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MalwareScannerRulesUrl
}

// GetMalwareScannerRulesUrlOk returns a tuple with the MalwareScannerRulesUrl field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetMalwareScannerRulesUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MalwareScannerRulesUrl, true
}

// SetMalwareScannerRulesUrl sets field value
func (o *ControlsThreatIntelInfo) SetMalwareScannerRulesUrl(v string) {
	o.MalwareScannerRulesUrl = v
}

// GetNetworkAlertRulesUrl returns the NetworkAlertRulesUrl field value
func (o *ControlsThreatIntelInfo) GetNetworkAlertRulesUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkAlertRulesUrl
}

// GetNetworkAlertRulesUrlOk returns a tuple with the NetworkAlertRulesUrl field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetNetworkAlertRulesUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkAlertRulesUrl, true
}

// SetNetworkAlertRulesUrl sets field value
func (o *ControlsThreatIntelInfo) SetNetworkAlertRulesUrl(v string) {
	o.NetworkAlertRulesUrl = v
}

// GetRulesHash returns the RulesHash field value
func (o *ControlsThreatIntelInfo) GetRulesHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RulesHash
}

// GetRulesHashOk returns a tuple with the RulesHash field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetRulesHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RulesHash, true
}

// SetRulesHash sets field value
func (o *ControlsThreatIntelInfo) SetRulesHash(v string) {
	o.RulesHash = v
}

// GetSecretScannerRulesHash returns the SecretScannerRulesHash field value
func (o *ControlsThreatIntelInfo) GetSecretScannerRulesHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretScannerRulesHash
}

// GetSecretScannerRulesHashOk returns a tuple with the SecretScannerRulesHash field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetSecretScannerRulesHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretScannerRulesHash, true
}

// SetSecretScannerRulesHash sets field value
func (o *ControlsThreatIntelInfo) SetSecretScannerRulesHash(v string) {
	o.SecretScannerRulesHash = v
}

// GetSecretScannerRulesUrl returns the SecretScannerRulesUrl field value
func (o *ControlsThreatIntelInfo) GetSecretScannerRulesUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretScannerRulesUrl
}

// GetSecretScannerRulesUrlOk returns a tuple with the SecretScannerRulesUrl field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetSecretScannerRulesUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretScannerRulesUrl, true
}

// SetSecretScannerRulesUrl sets field value
func (o *ControlsThreatIntelInfo) SetSecretScannerRulesUrl(v string) {
	o.SecretScannerRulesUrl = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ControlsThreatIntelInfo) GetUpdatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ControlsThreatIntelInfo) GetUpdatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ControlsThreatIntelInfo) SetUpdatedAt(v int32) {
	o.UpdatedAt = v
}

func (o ControlsThreatIntelInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlsThreatIntelInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloud_posture_controls_hash"] = o.CloudPostureControlsHash
	toSerialize["cloud_posture_controls_url"] = o.CloudPostureControlsUrl
	if o.IgnoredAlertRuleIds != nil {
		toSerialize["ignored_alert_rule_ids"] = o.IgnoredAlertRuleIds
	}
	if o.InternalIps != nil {
		toSerialize["internal_ips"] = o.InternalIps
	}
	toSerialize["malware_scanner_rules_hash"] = o.MalwareScannerRulesHash
	toSerialize["malware_scanner_rules_url"] = o.MalwareScannerRulesUrl
	toSerialize["network_alert_rules_url"] = o.NetworkAlertRulesUrl
	toSerialize["rules_hash"] = o.RulesHash
	toSerialize["secret_scanner_rules_hash"] = o.SecretScannerRulesHash
	toSerialize["secret_scanner_rules_url"] = o.SecretScannerRulesUrl
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ControlsThreatIntelInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloud_posture_controls_hash",
		"cloud_posture_controls_url",
		"ignored_alert_rule_ids",
		"internal_ips",
		"malware_scanner_rules_hash",
		"malware_scanner_rules_url",
		"network_alert_rules_url",
		"rules_hash",
		"secret_scanner_rules_hash",
		"secret_scanner_rules_url",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varControlsThreatIntelInfo := _ControlsThreatIntelInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varControlsThreatIntelInfo)

	if err != nil {
		return err
	}

	*o = ControlsThreatIntelInfo(varControlsThreatIntelInfo)

	return err
}

type NullableControlsThreatIntelInfo struct {
	value *ControlsThreatIntelInfo
	isSet bool
}

func (v NullableControlsThreatIntelInfo) Get() *ControlsThreatIntelInfo {
	return v.value
}

func (v *NullableControlsThreatIntelInfo) Set(val *ControlsThreatIntelInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableControlsThreatIntelInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableControlsThreatIntelInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlsThreatIntelInfo(val *ControlsThreatIntelInfo) *NullableControlsThreatIntelInfo {
	return &NullableControlsThreatIntelInfo{value: val, isSet: true}
}

func (v NullableControlsThreatIntelInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlsThreatIntelInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


