/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the ControlsNetworkRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlsNetworkRules{}

// ControlsNetworkRules struct for ControlsNetworkRules
type ControlsNetworkRules struct {
	Inbound []string `json:"inbound"`
	Outbound []string `json:"outbound"`
}

type _ControlsNetworkRules ControlsNetworkRules

// NewControlsNetworkRules instantiates a new ControlsNetworkRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlsNetworkRules(inbound []string, outbound []string) *ControlsNetworkRules {
	this := ControlsNetworkRules{}
	this.Inbound = inbound
	this.Outbound = outbound
	return &this
}

// NewControlsNetworkRulesWithDefaults instantiates a new ControlsNetworkRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlsNetworkRulesWithDefaults() *ControlsNetworkRules {
	this := ControlsNetworkRules{}
	return &this
}

// GetInbound returns the Inbound field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ControlsNetworkRules) GetInbound() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Inbound
}

// GetInboundOk returns a tuple with the Inbound field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ControlsNetworkRules) GetInboundOk() ([]string, bool) {
	if o == nil || IsNil(o.Inbound) {
		return nil, false
	}
	return o.Inbound, true
}

// SetInbound sets field value
func (o *ControlsNetworkRules) SetInbound(v []string) {
	o.Inbound = v
}

// GetOutbound returns the Outbound field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ControlsNetworkRules) GetOutbound() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Outbound
}

// GetOutboundOk returns a tuple with the Outbound field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ControlsNetworkRules) GetOutboundOk() ([]string, bool) {
	if o == nil || IsNil(o.Outbound) {
		return nil, false
	}
	return o.Outbound, true
}

// SetOutbound sets field value
func (o *ControlsNetworkRules) SetOutbound(v []string) {
	o.Outbound = v
}

func (o ControlsNetworkRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlsNetworkRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Inbound != nil {
		toSerialize["inbound"] = o.Inbound
	}
	if o.Outbound != nil {
		toSerialize["outbound"] = o.Outbound
	}
	return toSerialize, nil
}

func (o *ControlsNetworkRules) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inbound",
		"outbound",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varControlsNetworkRules := _ControlsNetworkRules{}

	err = json.Unmarshal(bytes, &varControlsNetworkRules)

	if err != nil {
		return err
	}

	*o = ControlsNetworkRules(varControlsNetworkRules)

	return err
}

type NullableControlsNetworkRules struct {
	value *ControlsNetworkRules
	isSet bool
}

func (v NullableControlsNetworkRules) Get() *ControlsNetworkRules {
	return v.value
}

func (v *NullableControlsNetworkRules) Set(val *ControlsNetworkRules) {
	v.value = val
	v.isSet = true
}

func (v NullableControlsNetworkRules) IsSet() bool {
	return v.isSet
}

func (v *NullableControlsNetworkRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlsNetworkRules(val *ControlsNetworkRules) *NullableControlsNetworkRules {
	return &NullableControlsNetworkRules{value: val, isSet: true}
}

func (v NullableControlsNetworkRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlsNetworkRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


