/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v2.5.1
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelDeleteFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelDeleteFilter{}

// ModelDeleteFilter struct for ModelDeleteFilter
type ModelDeleteFilter struct {
	NodeIds []string `json:"node_ids"`
}

type _ModelDeleteFilter ModelDeleteFilter

// NewModelDeleteFilter instantiates a new ModelDeleteFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelDeleteFilter(nodeIds []string) *ModelDeleteFilter {
	this := ModelDeleteFilter{}
	this.NodeIds = nodeIds
	return &this
}

// NewModelDeleteFilterWithDefaults instantiates a new ModelDeleteFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelDeleteFilterWithDefaults() *ModelDeleteFilter {
	this := ModelDeleteFilter{}
	return &this
}

// GetNodeIds returns the NodeIds field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ModelDeleteFilter) GetNodeIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.NodeIds
}

// GetNodeIdsOk returns a tuple with the NodeIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelDeleteFilter) GetNodeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.NodeIds) {
		return nil, false
	}
	return o.NodeIds, true
}

// SetNodeIds sets field value
func (o *ModelDeleteFilter) SetNodeIds(v []string) {
	o.NodeIds = v
}

func (o ModelDeleteFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelDeleteFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NodeIds != nil {
		toSerialize["node_ids"] = o.NodeIds
	}
	return toSerialize, nil
}

func (o *ModelDeleteFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelDeleteFilter := _ModelDeleteFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelDeleteFilter)

	if err != nil {
		return err
	}

	*o = ModelDeleteFilter(varModelDeleteFilter)

	return err
}

type NullableModelDeleteFilter struct {
	value *ModelDeleteFilter
	isSet bool
}

func (v NullableModelDeleteFilter) Get() *ModelDeleteFilter {
	return v.value
}

func (v *NullableModelDeleteFilter) Set(val *ModelDeleteFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableModelDeleteFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableModelDeleteFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelDeleteFilter(val *ModelDeleteFilter) *NullableModelDeleteFilter {
	return &NullableModelDeleteFilter{value: val, isSet: true}
}

func (v NullableModelDeleteFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelDeleteFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


