/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v3.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelNetworkViolationStub type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelNetworkViolationStub{}

// ModelNetworkViolationStub struct for ModelNetworkViolationStub
type ModelNetworkViolationStub struct {
	NodeId string `json:"node_id"`
}

type _ModelNetworkViolationStub ModelNetworkViolationStub

// NewModelNetworkViolationStub instantiates a new ModelNetworkViolationStub object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelNetworkViolationStub(nodeId string) *ModelNetworkViolationStub {
	this := ModelNetworkViolationStub{}
	this.NodeId = nodeId
	return &this
}

// NewModelNetworkViolationStubWithDefaults instantiates a new ModelNetworkViolationStub object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelNetworkViolationStubWithDefaults() *ModelNetworkViolationStub {
	this := ModelNetworkViolationStub{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *ModelNetworkViolationStub) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkViolationStub) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ModelNetworkViolationStub) SetNodeId(v string) {
	o.NodeId = v
}

func (o ModelNetworkViolationStub) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelNetworkViolationStub) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node_id"] = o.NodeId
	return toSerialize, nil
}

func (o *ModelNetworkViolationStub) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelNetworkViolationStub := _ModelNetworkViolationStub{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelNetworkViolationStub)

	if err != nil {
		return err
	}

	*o = ModelNetworkViolationStub(varModelNetworkViolationStub)

	return err
}

type NullableModelNetworkViolationStub struct {
	value *ModelNetworkViolationStub
	isSet bool
}

func (v NullableModelNetworkViolationStub) Get() *ModelNetworkViolationStub {
	return v.value
}

func (v *NullableModelNetworkViolationStub) Set(val *ModelNetworkViolationStub) {
	v.value = val
	v.isSet = true
}

func (v NullableModelNetworkViolationStub) IsSet() bool {
	return v.isSet
}

func (v *NullableModelNetworkViolationStub) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelNetworkViolationStub(val *ModelNetworkViolationStub) *NullableModelNetworkViolationStub {
	return &NullableModelNetworkViolationStub{value: val, isSet: true}
}

func (v NullableModelNetworkViolationStub) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelNetworkViolationStub) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


