/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelEnableNetworkTracerReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelEnableNetworkTracerReq{}

// ModelEnableNetworkTracerReq struct for ModelEnableNetworkTracerReq
type ModelEnableNetworkTracerReq struct {
	AgentIds []ModelAgentId `json:"agent_ids"`
}

// NewModelEnableNetworkTracerReq instantiates a new ModelEnableNetworkTracerReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelEnableNetworkTracerReq(agentIds []ModelAgentId) *ModelEnableNetworkTracerReq {
	this := ModelEnableNetworkTracerReq{}
	this.AgentIds = agentIds
	return &this
}

// NewModelEnableNetworkTracerReqWithDefaults instantiates a new ModelEnableNetworkTracerReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelEnableNetworkTracerReqWithDefaults() *ModelEnableNetworkTracerReq {
	this := ModelEnableNetworkTracerReq{}
	return &this
}

// GetAgentIds returns the AgentIds field value
// If the value is explicit nil, the zero value for []ModelAgentId will be returned
func (o *ModelEnableNetworkTracerReq) GetAgentIds() []ModelAgentId {
	if o == nil {
		var ret []ModelAgentId
		return ret
	}

	return o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelEnableNetworkTracerReq) GetAgentIdsOk() ([]ModelAgentId, bool) {
	if o == nil || IsNil(o.AgentIds) {
		return nil, false
	}
	return o.AgentIds, true
}

// SetAgentIds sets field value
func (o *ModelEnableNetworkTracerReq) SetAgentIds(v []ModelAgentId) {
	o.AgentIds = v
}

func (o ModelEnableNetworkTracerReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelEnableNetworkTracerReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AgentIds != nil {
		toSerialize["agent_ids"] = o.AgentIds
	}
	return toSerialize, nil
}

type NullableModelEnableNetworkTracerReq struct {
	value *ModelEnableNetworkTracerReq
	isSet bool
}

func (v NullableModelEnableNetworkTracerReq) Get() *ModelEnableNetworkTracerReq {
	return v.value
}

func (v *NullableModelEnableNetworkTracerReq) Set(val *ModelEnableNetworkTracerReq) {
	v.value = val
	v.isSet = true
}

func (v NullableModelEnableNetworkTracerReq) IsSet() bool {
	return v.isSet
}

func (v *NullableModelEnableNetworkTracerReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelEnableNetworkTracerReq(val *ModelEnableNetworkTracerReq) *NullableModelEnableNetworkTracerReq {
	return &NullableModelEnableNetworkTracerReq{value: val, isSet: true}
}

func (v NullableModelEnableNetworkTracerReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelEnableNetworkTracerReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


