/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v2.5.1
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelNetworkAlert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelNetworkAlert{}

// ModelNetworkAlert struct for ModelNetworkAlert
type ModelNetworkAlert struct {
	Base64Payload string `json:"base_64_payload"`
	Category string `json:"category"`
	ContainerName string `json:"container_name"`
	Count int32 `json:"count"`
	CreatedAt int32 `json:"created_at"`
	DestinationIp string `json:"destination_ip"`
	DestinationPort int32 `json:"destination_port"`
	Direction string `json:"direction"`
	Encrypted bool `json:"encrypted"`
	EventType string `json:"event_type"`
	Headers string `json:"headers"`
	HostName string `json:"host_name"`
	HttpType string `json:"http_type"`
	KubernetesClusterId string `json:"kubernetes_cluster_id"`
	KubernetesClusterName string `json:"kubernetes_cluster_name"`
	Masked bool `json:"masked"`
	NodeId string `json:"node_id"`
	NodeType string `json:"node_type"`
	Payload string `json:"payload"`
	PodName string `json:"pod_name"`
	Protocol string `json:"protocol"`
	References string `json:"references"`
	Request *string `json:"request,omitempty"`
	Response *string `json:"response,omitempty"`
	RuleId string `json:"rule_id"`
	Severity string `json:"severity"`
	SourceIp string `json:"source_ip"`
	SourcePort int32 `json:"source_port"`
	Summary string `json:"summary"`
	Tactics []string `json:"tactics"`
	Tags string `json:"tags"`
	Techniques []string `json:"techniques"`
	UpdatedAt int32 `json:"updated_at"`
	Url string `json:"url"`
}

type _ModelNetworkAlert ModelNetworkAlert

// NewModelNetworkAlert instantiates a new ModelNetworkAlert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelNetworkAlert(base64Payload string, category string, containerName string, count int32, createdAt int32, destinationIp string, destinationPort int32, direction string, encrypted bool, eventType string, headers string, hostName string, httpType string, kubernetesClusterId string, kubernetesClusterName string, masked bool, nodeId string, nodeType string, payload string, podName string, protocol string, references string, ruleId string, severity string, sourceIp string, sourcePort int32, summary string, tactics []string, tags string, techniques []string, updatedAt int32, url string) *ModelNetworkAlert {
	this := ModelNetworkAlert{}
	this.Base64Payload = base64Payload
	this.Category = category
	this.ContainerName = containerName
	this.Count = count
	this.CreatedAt = createdAt
	this.DestinationIp = destinationIp
	this.DestinationPort = destinationPort
	this.Direction = direction
	this.Encrypted = encrypted
	this.EventType = eventType
	this.Headers = headers
	this.HostName = hostName
	this.HttpType = httpType
	this.KubernetesClusterId = kubernetesClusterId
	this.KubernetesClusterName = kubernetesClusterName
	this.Masked = masked
	this.NodeId = nodeId
	this.NodeType = nodeType
	this.Payload = payload
	this.PodName = podName
	this.Protocol = protocol
	this.References = references
	this.RuleId = ruleId
	this.Severity = severity
	this.SourceIp = sourceIp
	this.SourcePort = sourcePort
	this.Summary = summary
	this.Tactics = tactics
	this.Tags = tags
	this.Techniques = techniques
	this.UpdatedAt = updatedAt
	this.Url = url
	return &this
}

// NewModelNetworkAlertWithDefaults instantiates a new ModelNetworkAlert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelNetworkAlertWithDefaults() *ModelNetworkAlert {
	this := ModelNetworkAlert{}
	return &this
}

// GetBase64Payload returns the Base64Payload field value
func (o *ModelNetworkAlert) GetBase64Payload() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Base64Payload
}

// GetBase64PayloadOk returns a tuple with the Base64Payload field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetBase64PayloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Base64Payload, true
}

// SetBase64Payload sets field value
func (o *ModelNetworkAlert) SetBase64Payload(v string) {
	o.Base64Payload = v
}

// GetCategory returns the Category field value
func (o *ModelNetworkAlert) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *ModelNetworkAlert) SetCategory(v string) {
	o.Category = v
}

// GetContainerName returns the ContainerName field value
func (o *ModelNetworkAlert) GetContainerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerName
}

// GetContainerNameOk returns a tuple with the ContainerName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerName, true
}

// SetContainerName sets field value
func (o *ModelNetworkAlert) SetContainerName(v string) {
	o.ContainerName = v
}

// GetCount returns the Count field value
func (o *ModelNetworkAlert) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ModelNetworkAlert) SetCount(v int32) {
	o.Count = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ModelNetworkAlert) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ModelNetworkAlert) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

// GetDestinationIp returns the DestinationIp field value
func (o *ModelNetworkAlert) GetDestinationIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationIp
}

// GetDestinationIpOk returns a tuple with the DestinationIp field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetDestinationIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationIp, true
}

// SetDestinationIp sets field value
func (o *ModelNetworkAlert) SetDestinationIp(v string) {
	o.DestinationIp = v
}

// GetDestinationPort returns the DestinationPort field value
func (o *ModelNetworkAlert) GetDestinationPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DestinationPort
}

// GetDestinationPortOk returns a tuple with the DestinationPort field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetDestinationPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationPort, true
}

// SetDestinationPort sets field value
func (o *ModelNetworkAlert) SetDestinationPort(v int32) {
	o.DestinationPort = v
}

// GetDirection returns the Direction field value
func (o *ModelNetworkAlert) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *ModelNetworkAlert) SetDirection(v string) {
	o.Direction = v
}

// GetEncrypted returns the Encrypted field value
func (o *ModelNetworkAlert) GetEncrypted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Encrypted
}

// GetEncryptedOk returns a tuple with the Encrypted field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetEncryptedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Encrypted, true
}

// SetEncrypted sets field value
func (o *ModelNetworkAlert) SetEncrypted(v bool) {
	o.Encrypted = v
}

// GetEventType returns the EventType field value
func (o *ModelNetworkAlert) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *ModelNetworkAlert) SetEventType(v string) {
	o.EventType = v
}

// GetHeaders returns the Headers field value
func (o *ModelNetworkAlert) GetHeaders() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetHeadersOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Headers, true
}

// SetHeaders sets field value
func (o *ModelNetworkAlert) SetHeaders(v string) {
	o.Headers = v
}

// GetHostName returns the HostName field value
func (o *ModelNetworkAlert) GetHostName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetHostNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostName, true
}

// SetHostName sets field value
func (o *ModelNetworkAlert) SetHostName(v string) {
	o.HostName = v
}

// GetHttpType returns the HttpType field value
func (o *ModelNetworkAlert) GetHttpType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HttpType
}

// GetHttpTypeOk returns a tuple with the HttpType field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetHttpTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HttpType, true
}

// SetHttpType sets field value
func (o *ModelNetworkAlert) SetHttpType(v string) {
	o.HttpType = v
}

// GetKubernetesClusterId returns the KubernetesClusterId field value
func (o *ModelNetworkAlert) GetKubernetesClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubernetesClusterId
}

// GetKubernetesClusterIdOk returns a tuple with the KubernetesClusterId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetKubernetesClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubernetesClusterId, true
}

// SetKubernetesClusterId sets field value
func (o *ModelNetworkAlert) SetKubernetesClusterId(v string) {
	o.KubernetesClusterId = v
}

// GetKubernetesClusterName returns the KubernetesClusterName field value
func (o *ModelNetworkAlert) GetKubernetesClusterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubernetesClusterName
}

// GetKubernetesClusterNameOk returns a tuple with the KubernetesClusterName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetKubernetesClusterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubernetesClusterName, true
}

// SetKubernetesClusterName sets field value
func (o *ModelNetworkAlert) SetKubernetesClusterName(v string) {
	o.KubernetesClusterName = v
}

// GetMasked returns the Masked field value
func (o *ModelNetworkAlert) GetMasked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Masked
}

// GetMaskedOk returns a tuple with the Masked field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetMaskedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Masked, true
}

// SetMasked sets field value
func (o *ModelNetworkAlert) SetMasked(v bool) {
	o.Masked = v
}

// GetNodeId returns the NodeId field value
func (o *ModelNetworkAlert) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ModelNetworkAlert) SetNodeId(v string) {
	o.NodeId = v
}

// GetNodeType returns the NodeType field value
func (o *ModelNetworkAlert) GetNodeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeType
}

// GetNodeTypeOk returns a tuple with the NodeType field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetNodeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeType, true
}

// SetNodeType sets field value
func (o *ModelNetworkAlert) SetNodeType(v string) {
	o.NodeType = v
}

// GetPayload returns the Payload field value
func (o *ModelNetworkAlert) GetPayload() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetPayloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *ModelNetworkAlert) SetPayload(v string) {
	o.Payload = v
}

// GetPodName returns the PodName field value
func (o *ModelNetworkAlert) GetPodName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PodName
}

// GetPodNameOk returns a tuple with the PodName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetPodNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PodName, true
}

// SetPodName sets field value
func (o *ModelNetworkAlert) SetPodName(v string) {
	o.PodName = v
}

// GetProtocol returns the Protocol field value
func (o *ModelNetworkAlert) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *ModelNetworkAlert) SetProtocol(v string) {
	o.Protocol = v
}

// GetReferences returns the References field value
func (o *ModelNetworkAlert) GetReferences() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.References
}

// GetReferencesOk returns a tuple with the References field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetReferencesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.References, true
}

// SetReferences sets field value
func (o *ModelNetworkAlert) SetReferences(v string) {
	o.References = v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ModelNetworkAlert) GetRequest() string {
	if o == nil || IsNil(o.Request) {
		var ret string
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetRequestOk() (*string, bool) {
	if o == nil || IsNil(o.Request) {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ModelNetworkAlert) HasRequest() bool {
	if o != nil && !IsNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given string and assigns it to the Request field.
func (o *ModelNetworkAlert) SetRequest(v string) {
	o.Request = &v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *ModelNetworkAlert) GetResponse() string {
	if o == nil || IsNil(o.Response) {
		var ret string
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetResponseOk() (*string, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *ModelNetworkAlert) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given string and assigns it to the Response field.
func (o *ModelNetworkAlert) SetResponse(v string) {
	o.Response = &v
}

// GetRuleId returns the RuleId field value
func (o *ModelNetworkAlert) GetRuleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetRuleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleId, true
}

// SetRuleId sets field value
func (o *ModelNetworkAlert) SetRuleId(v string) {
	o.RuleId = v
}

// GetSeverity returns the Severity field value
func (o *ModelNetworkAlert) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ModelNetworkAlert) SetSeverity(v string) {
	o.Severity = v
}

// GetSourceIp returns the SourceIp field value
func (o *ModelNetworkAlert) GetSourceIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceIp
}

// GetSourceIpOk returns a tuple with the SourceIp field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSourceIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceIp, true
}

// SetSourceIp sets field value
func (o *ModelNetworkAlert) SetSourceIp(v string) {
	o.SourceIp = v
}

// GetSourcePort returns the SourcePort field value
func (o *ModelNetworkAlert) GetSourcePort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SourcePort
}

// GetSourcePortOk returns a tuple with the SourcePort field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSourcePortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourcePort, true
}

// SetSourcePort sets field value
func (o *ModelNetworkAlert) SetSourcePort(v int32) {
	o.SourcePort = v
}

// GetSummary returns the Summary field value
func (o *ModelNetworkAlert) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *ModelNetworkAlert) SetSummary(v string) {
	o.Summary = v
}

// GetTactics returns the Tactics field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ModelNetworkAlert) GetTactics() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tactics
}

// GetTacticsOk returns a tuple with the Tactics field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelNetworkAlert) GetTacticsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tactics) {
		return nil, false
	}
	return o.Tactics, true
}

// SetTactics sets field value
func (o *ModelNetworkAlert) SetTactics(v []string) {
	o.Tactics = v
}

// GetTags returns the Tags field value
func (o *ModelNetworkAlert) GetTags() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetTagsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *ModelNetworkAlert) SetTags(v string) {
	o.Tags = v
}

// GetTechniques returns the Techniques field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ModelNetworkAlert) GetTechniques() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Techniques
}

// GetTechniquesOk returns a tuple with the Techniques field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelNetworkAlert) GetTechniquesOk() ([]string, bool) {
	if o == nil || IsNil(o.Techniques) {
		return nil, false
	}
	return o.Techniques, true
}

// SetTechniques sets field value
func (o *ModelNetworkAlert) SetTechniques(v []string) {
	o.Techniques = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ModelNetworkAlert) GetUpdatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetUpdatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ModelNetworkAlert) SetUpdatedAt(v int32) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *ModelNetworkAlert) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ModelNetworkAlert) SetUrl(v string) {
	o.Url = v
}

func (o ModelNetworkAlert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelNetworkAlert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base_64_payload"] = o.Base64Payload
	toSerialize["category"] = o.Category
	toSerialize["container_name"] = o.ContainerName
	toSerialize["count"] = o.Count
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["destination_ip"] = o.DestinationIp
	toSerialize["destination_port"] = o.DestinationPort
	toSerialize["direction"] = o.Direction
	toSerialize["encrypted"] = o.Encrypted
	toSerialize["event_type"] = o.EventType
	toSerialize["headers"] = o.Headers
	toSerialize["host_name"] = o.HostName
	toSerialize["http_type"] = o.HttpType
	toSerialize["kubernetes_cluster_id"] = o.KubernetesClusterId
	toSerialize["kubernetes_cluster_name"] = o.KubernetesClusterName
	toSerialize["masked"] = o.Masked
	toSerialize["node_id"] = o.NodeId
	toSerialize["node_type"] = o.NodeType
	toSerialize["payload"] = o.Payload
	toSerialize["pod_name"] = o.PodName
	toSerialize["protocol"] = o.Protocol
	toSerialize["references"] = o.References
	if !IsNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	toSerialize["rule_id"] = o.RuleId
	toSerialize["severity"] = o.Severity
	toSerialize["source_ip"] = o.SourceIp
	toSerialize["source_port"] = o.SourcePort
	toSerialize["summary"] = o.Summary
	if o.Tactics != nil {
		toSerialize["tactics"] = o.Tactics
	}
	toSerialize["tags"] = o.Tags
	if o.Techniques != nil {
		toSerialize["techniques"] = o.Techniques
	}
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ModelNetworkAlert) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base_64_payload",
		"category",
		"container_name",
		"count",
		"created_at",
		"destination_ip",
		"destination_port",
		"direction",
		"encrypted",
		"event_type",
		"headers",
		"host_name",
		"http_type",
		"kubernetes_cluster_id",
		"kubernetes_cluster_name",
		"masked",
		"node_id",
		"node_type",
		"payload",
		"pod_name",
		"protocol",
		"references",
		"rule_id",
		"severity",
		"source_ip",
		"source_port",
		"summary",
		"tactics",
		"tags",
		"techniques",
		"updated_at",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelNetworkAlert := _ModelNetworkAlert{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelNetworkAlert)

	if err != nil {
		return err
	}

	*o = ModelNetworkAlert(varModelNetworkAlert)

	return err
}

type NullableModelNetworkAlert struct {
	value *ModelNetworkAlert
	isSet bool
}

func (v NullableModelNetworkAlert) Get() *ModelNetworkAlert {
	return v.value
}

func (v *NullableModelNetworkAlert) Set(val *ModelNetworkAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableModelNetworkAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableModelNetworkAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelNetworkAlert(val *ModelNetworkAlert) *NullableModelNetworkAlert {
	return &NullableModelNetworkAlert{value: val, isSet: true}
}

func (v NullableModelNetworkAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelNetworkAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


