/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelNetworkAlert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelNetworkAlert{}

// ModelNetworkAlert struct for ModelNetworkAlert
type ModelNetworkAlert struct {
	AppProto string `json:"app_proto"`
	Category string `json:"category"`
	Classtype string `json:"classtype"`
	ContainerName string `json:"container_name"`
	Count int32 `json:"count"`
	CreatedAt int32 `json:"created_at"`
	Description string `json:"description"`
	DestinationIp string `json:"destination_ip"`
	DestinationPort int32 `json:"destination_port"`
	Direction string `json:"direction"`
	Encrypted string `json:"encrypted"`
	EventType string `json:"event_type"`
	Geoip *ModelNetworkAlertGeoip `json:"geoip,omitempty"`
	Hostname string `json:"hostname"`
	Http *ModelNetworkAlertHttp `json:"http,omitempty"`
	HttpType string `json:"http_type"`
	Intent string `json:"intent"`
	Internal string `json:"internal"`
	IpReputation string `json:"ip_reputation"`
	KubernetesClusterName string `json:"kubernetes_cluster_name"`
	Masked bool `json:"masked"`
	Matched string `json:"matched"`
	NodeId string `json:"node_id"`
	NodeType string `json:"node_type"`
	PodName string `json:"pod_name"`
	ResourceType string `json:"resource_type"`
	RuleId int32 `json:"rule_id"`
	ScopeId string `json:"scope_id"`
	Severity string `json:"severity"`
	SeverityAnomalyContainerName string `json:"severity_anomaly_container_name"`
	SeverityScore float32 `json:"severity_score"`
	SignatureId int32 `json:"signature_id"`
	SourceIp string `json:"source_ip"`
	SourcePort int32 `json:"source_port"`
	Summary string `json:"summary"`
	Tags string `json:"tags"`
	UpdatedAt int32 `json:"updated_at"`
}

// NewModelNetworkAlert instantiates a new ModelNetworkAlert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelNetworkAlert(appProto string, category string, classtype string, containerName string, count int32, createdAt int32, description string, destinationIp string, destinationPort int32, direction string, encrypted string, eventType string, hostname string, httpType string, intent string, internal string, ipReputation string, kubernetesClusterName string, masked bool, matched string, nodeId string, nodeType string, podName string, resourceType string, ruleId int32, scopeId string, severity string, severityAnomalyContainerName string, severityScore float32, signatureId int32, sourceIp string, sourcePort int32, summary string, tags string, updatedAt int32) *ModelNetworkAlert {
	this := ModelNetworkAlert{}
	this.AppProto = appProto
	this.Category = category
	this.Classtype = classtype
	this.ContainerName = containerName
	this.Count = count
	this.CreatedAt = createdAt
	this.Description = description
	this.DestinationIp = destinationIp
	this.DestinationPort = destinationPort
	this.Direction = direction
	this.Encrypted = encrypted
	this.EventType = eventType
	this.Hostname = hostname
	this.HttpType = httpType
	this.Intent = intent
	this.Internal = internal
	this.IpReputation = ipReputation
	this.KubernetesClusterName = kubernetesClusterName
	this.Masked = masked
	this.Matched = matched
	this.NodeId = nodeId
	this.NodeType = nodeType
	this.PodName = podName
	this.ResourceType = resourceType
	this.RuleId = ruleId
	this.ScopeId = scopeId
	this.Severity = severity
	this.SeverityAnomalyContainerName = severityAnomalyContainerName
	this.SeverityScore = severityScore
	this.SignatureId = signatureId
	this.SourceIp = sourceIp
	this.SourcePort = sourcePort
	this.Summary = summary
	this.Tags = tags
	this.UpdatedAt = updatedAt
	return &this
}

// NewModelNetworkAlertWithDefaults instantiates a new ModelNetworkAlert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelNetworkAlertWithDefaults() *ModelNetworkAlert {
	this := ModelNetworkAlert{}
	return &this
}

// GetAppProto returns the AppProto field value
func (o *ModelNetworkAlert) GetAppProto() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppProto
}

// GetAppProtoOk returns a tuple with the AppProto field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetAppProtoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppProto, true
}

// SetAppProto sets field value
func (o *ModelNetworkAlert) SetAppProto(v string) {
	o.AppProto = v
}

// GetCategory returns the Category field value
func (o *ModelNetworkAlert) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *ModelNetworkAlert) SetCategory(v string) {
	o.Category = v
}

// GetClasstype returns the Classtype field value
func (o *ModelNetworkAlert) GetClasstype() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Classtype
}

// GetClasstypeOk returns a tuple with the Classtype field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetClasstypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Classtype, true
}

// SetClasstype sets field value
func (o *ModelNetworkAlert) SetClasstype(v string) {
	o.Classtype = v
}

// GetContainerName returns the ContainerName field value
func (o *ModelNetworkAlert) GetContainerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerName
}

// GetContainerNameOk returns a tuple with the ContainerName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerName, true
}

// SetContainerName sets field value
func (o *ModelNetworkAlert) SetContainerName(v string) {
	o.ContainerName = v
}

// GetCount returns the Count field value
func (o *ModelNetworkAlert) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ModelNetworkAlert) SetCount(v int32) {
	o.Count = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ModelNetworkAlert) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ModelNetworkAlert) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

// GetDescription returns the Description field value
func (o *ModelNetworkAlert) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ModelNetworkAlert) SetDescription(v string) {
	o.Description = v
}

// GetDestinationIp returns the DestinationIp field value
func (o *ModelNetworkAlert) GetDestinationIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationIp
}

// GetDestinationIpOk returns a tuple with the DestinationIp field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetDestinationIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationIp, true
}

// SetDestinationIp sets field value
func (o *ModelNetworkAlert) SetDestinationIp(v string) {
	o.DestinationIp = v
}

// GetDestinationPort returns the DestinationPort field value
func (o *ModelNetworkAlert) GetDestinationPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DestinationPort
}

// GetDestinationPortOk returns a tuple with the DestinationPort field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetDestinationPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationPort, true
}

// SetDestinationPort sets field value
func (o *ModelNetworkAlert) SetDestinationPort(v int32) {
	o.DestinationPort = v
}

// GetDirection returns the Direction field value
func (o *ModelNetworkAlert) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *ModelNetworkAlert) SetDirection(v string) {
	o.Direction = v
}

// GetEncrypted returns the Encrypted field value
func (o *ModelNetworkAlert) GetEncrypted() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Encrypted
}

// GetEncryptedOk returns a tuple with the Encrypted field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetEncryptedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Encrypted, true
}

// SetEncrypted sets field value
func (o *ModelNetworkAlert) SetEncrypted(v string) {
	o.Encrypted = v
}

// GetEventType returns the EventType field value
func (o *ModelNetworkAlert) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *ModelNetworkAlert) SetEventType(v string) {
	o.EventType = v
}

// GetGeoip returns the Geoip field value if set, zero value otherwise.
func (o *ModelNetworkAlert) GetGeoip() ModelNetworkAlertGeoip {
	if o == nil || IsNil(o.Geoip) {
		var ret ModelNetworkAlertGeoip
		return ret
	}
	return *o.Geoip
}

// GetGeoipOk returns a tuple with the Geoip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetGeoipOk() (*ModelNetworkAlertGeoip, bool) {
	if o == nil || IsNil(o.Geoip) {
		return nil, false
	}
	return o.Geoip, true
}

// HasGeoip returns a boolean if a field has been set.
func (o *ModelNetworkAlert) HasGeoip() bool {
	if o != nil && !IsNil(o.Geoip) {
		return true
	}

	return false
}

// SetGeoip gets a reference to the given ModelNetworkAlertGeoip and assigns it to the Geoip field.
func (o *ModelNetworkAlert) SetGeoip(v ModelNetworkAlertGeoip) {
	o.Geoip = &v
}

// GetHostname returns the Hostname field value
func (o *ModelNetworkAlert) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *ModelNetworkAlert) SetHostname(v string) {
	o.Hostname = v
}

// GetHttp returns the Http field value if set, zero value otherwise.
func (o *ModelNetworkAlert) GetHttp() ModelNetworkAlertHttp {
	if o == nil || IsNil(o.Http) {
		var ret ModelNetworkAlertHttp
		return ret
	}
	return *o.Http
}

// GetHttpOk returns a tuple with the Http field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetHttpOk() (*ModelNetworkAlertHttp, bool) {
	if o == nil || IsNil(o.Http) {
		return nil, false
	}
	return o.Http, true
}

// HasHttp returns a boolean if a field has been set.
func (o *ModelNetworkAlert) HasHttp() bool {
	if o != nil && !IsNil(o.Http) {
		return true
	}

	return false
}

// SetHttp gets a reference to the given ModelNetworkAlertHttp and assigns it to the Http field.
func (o *ModelNetworkAlert) SetHttp(v ModelNetworkAlertHttp) {
	o.Http = &v
}

// GetHttpType returns the HttpType field value
func (o *ModelNetworkAlert) GetHttpType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HttpType
}

// GetHttpTypeOk returns a tuple with the HttpType field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetHttpTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HttpType, true
}

// SetHttpType sets field value
func (o *ModelNetworkAlert) SetHttpType(v string) {
	o.HttpType = v
}

// GetIntent returns the Intent field value
func (o *ModelNetworkAlert) GetIntent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Intent
}

// GetIntentOk returns a tuple with the Intent field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetIntentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Intent, true
}

// SetIntent sets field value
func (o *ModelNetworkAlert) SetIntent(v string) {
	o.Intent = v
}

// GetInternal returns the Internal field value
func (o *ModelNetworkAlert) GetInternal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Internal
}

// GetInternalOk returns a tuple with the Internal field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetInternalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Internal, true
}

// SetInternal sets field value
func (o *ModelNetworkAlert) SetInternal(v string) {
	o.Internal = v
}

// GetIpReputation returns the IpReputation field value
func (o *ModelNetworkAlert) GetIpReputation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpReputation
}

// GetIpReputationOk returns a tuple with the IpReputation field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetIpReputationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpReputation, true
}

// SetIpReputation sets field value
func (o *ModelNetworkAlert) SetIpReputation(v string) {
	o.IpReputation = v
}

// GetKubernetesClusterName returns the KubernetesClusterName field value
func (o *ModelNetworkAlert) GetKubernetesClusterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubernetesClusterName
}

// GetKubernetesClusterNameOk returns a tuple with the KubernetesClusterName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetKubernetesClusterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubernetesClusterName, true
}

// SetKubernetesClusterName sets field value
func (o *ModelNetworkAlert) SetKubernetesClusterName(v string) {
	o.KubernetesClusterName = v
}

// GetMasked returns the Masked field value
func (o *ModelNetworkAlert) GetMasked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Masked
}

// GetMaskedOk returns a tuple with the Masked field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetMaskedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Masked, true
}

// SetMasked sets field value
func (o *ModelNetworkAlert) SetMasked(v bool) {
	o.Masked = v
}

// GetMatched returns the Matched field value
func (o *ModelNetworkAlert) GetMatched() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Matched
}

// GetMatchedOk returns a tuple with the Matched field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetMatchedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Matched, true
}

// SetMatched sets field value
func (o *ModelNetworkAlert) SetMatched(v string) {
	o.Matched = v
}

// GetNodeId returns the NodeId field value
func (o *ModelNetworkAlert) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ModelNetworkAlert) SetNodeId(v string) {
	o.NodeId = v
}

// GetNodeType returns the NodeType field value
func (o *ModelNetworkAlert) GetNodeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeType
}

// GetNodeTypeOk returns a tuple with the NodeType field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetNodeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeType, true
}

// SetNodeType sets field value
func (o *ModelNetworkAlert) SetNodeType(v string) {
	o.NodeType = v
}

// GetPodName returns the PodName field value
func (o *ModelNetworkAlert) GetPodName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PodName
}

// GetPodNameOk returns a tuple with the PodName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetPodNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PodName, true
}

// SetPodName sets field value
func (o *ModelNetworkAlert) SetPodName(v string) {
	o.PodName = v
}

// GetResourceType returns the ResourceType field value
func (o *ModelNetworkAlert) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ModelNetworkAlert) SetResourceType(v string) {
	o.ResourceType = v
}

// GetRuleId returns the RuleId field value
func (o *ModelNetworkAlert) GetRuleId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetRuleIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleId, true
}

// SetRuleId sets field value
func (o *ModelNetworkAlert) SetRuleId(v int32) {
	o.RuleId = v
}

// GetScopeId returns the ScopeId field value
func (o *ModelNetworkAlert) GetScopeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetScopeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeId, true
}

// SetScopeId sets field value
func (o *ModelNetworkAlert) SetScopeId(v string) {
	o.ScopeId = v
}

// GetSeverity returns the Severity field value
func (o *ModelNetworkAlert) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ModelNetworkAlert) SetSeverity(v string) {
	o.Severity = v
}

// GetSeverityAnomalyContainerName returns the SeverityAnomalyContainerName field value
func (o *ModelNetworkAlert) GetSeverityAnomalyContainerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SeverityAnomalyContainerName
}

// GetSeverityAnomalyContainerNameOk returns a tuple with the SeverityAnomalyContainerName field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSeverityAnomalyContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeverityAnomalyContainerName, true
}

// SetSeverityAnomalyContainerName sets field value
func (o *ModelNetworkAlert) SetSeverityAnomalyContainerName(v string) {
	o.SeverityAnomalyContainerName = v
}

// GetSeverityScore returns the SeverityScore field value
func (o *ModelNetworkAlert) GetSeverityScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SeverityScore
}

// GetSeverityScoreOk returns a tuple with the SeverityScore field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSeverityScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeverityScore, true
}

// SetSeverityScore sets field value
func (o *ModelNetworkAlert) SetSeverityScore(v float32) {
	o.SeverityScore = v
}

// GetSignatureId returns the SignatureId field value
func (o *ModelNetworkAlert) GetSignatureId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SignatureId
}

// GetSignatureIdOk returns a tuple with the SignatureId field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSignatureIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignatureId, true
}

// SetSignatureId sets field value
func (o *ModelNetworkAlert) SetSignatureId(v int32) {
	o.SignatureId = v
}

// GetSourceIp returns the SourceIp field value
func (o *ModelNetworkAlert) GetSourceIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceIp
}

// GetSourceIpOk returns a tuple with the SourceIp field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSourceIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceIp, true
}

// SetSourceIp sets field value
func (o *ModelNetworkAlert) SetSourceIp(v string) {
	o.SourceIp = v
}

// GetSourcePort returns the SourcePort field value
func (o *ModelNetworkAlert) GetSourcePort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SourcePort
}

// GetSourcePortOk returns a tuple with the SourcePort field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSourcePortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourcePort, true
}

// SetSourcePort sets field value
func (o *ModelNetworkAlert) SetSourcePort(v int32) {
	o.SourcePort = v
}

// GetSummary returns the Summary field value
func (o *ModelNetworkAlert) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *ModelNetworkAlert) SetSummary(v string) {
	o.Summary = v
}

// GetTags returns the Tags field value
func (o *ModelNetworkAlert) GetTags() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetTagsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *ModelNetworkAlert) SetTags(v string) {
	o.Tags = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ModelNetworkAlert) GetUpdatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ModelNetworkAlert) GetUpdatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ModelNetworkAlert) SetUpdatedAt(v int32) {
	o.UpdatedAt = v
}

func (o ModelNetworkAlert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelNetworkAlert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_proto"] = o.AppProto
	toSerialize["category"] = o.Category
	toSerialize["classtype"] = o.Classtype
	toSerialize["container_name"] = o.ContainerName
	toSerialize["count"] = o.Count
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["description"] = o.Description
	toSerialize["destination_ip"] = o.DestinationIp
	toSerialize["destination_port"] = o.DestinationPort
	toSerialize["direction"] = o.Direction
	toSerialize["encrypted"] = o.Encrypted
	toSerialize["event_type"] = o.EventType
	if !IsNil(o.Geoip) {
		toSerialize["geoip"] = o.Geoip
	}
	toSerialize["hostname"] = o.Hostname
	if !IsNil(o.Http) {
		toSerialize["http"] = o.Http
	}
	toSerialize["http_type"] = o.HttpType
	toSerialize["intent"] = o.Intent
	toSerialize["internal"] = o.Internal
	toSerialize["ip_reputation"] = o.IpReputation
	toSerialize["kubernetes_cluster_name"] = o.KubernetesClusterName
	toSerialize["masked"] = o.Masked
	toSerialize["matched"] = o.Matched
	toSerialize["node_id"] = o.NodeId
	toSerialize["node_type"] = o.NodeType
	toSerialize["pod_name"] = o.PodName
	toSerialize["resource_type"] = o.ResourceType
	toSerialize["rule_id"] = o.RuleId
	toSerialize["scope_id"] = o.ScopeId
	toSerialize["severity"] = o.Severity
	toSerialize["severity_anomaly_container_name"] = o.SeverityAnomalyContainerName
	toSerialize["severity_score"] = o.SeverityScore
	toSerialize["signature_id"] = o.SignatureId
	toSerialize["source_ip"] = o.SourceIp
	toSerialize["source_port"] = o.SourcePort
	toSerialize["summary"] = o.Summary
	toSerialize["tags"] = o.Tags
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

type NullableModelNetworkAlert struct {
	value *ModelNetworkAlert
	isSet bool
}

func (v NullableModelNetworkAlert) Get() *ModelNetworkAlert {
	return v.value
}

func (v *NullableModelNetworkAlert) Set(val *ModelNetworkAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableModelNetworkAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableModelNetworkAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelNetworkAlert(val *ModelNetworkAlert) *NullableModelNetworkAlert {
	return &NullableModelNetworkAlert{value: val, isSet: true}
}

func (v NullableModelNetworkAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelNetworkAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


