/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelFileAlert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelFileAlert{}

// ModelFileAlert struct for ModelFileAlert
type ModelFileAlert struct {
	Category string `json:"category"`
	ContainerId string `json:"container_id"`
	ContainerImage string `json:"container_image"`
	ContainerIp string `json:"container_ip"`
	ContainerName string `json:"container_name"`
	Count int32 `json:"count"`
	CreatedAt int32 `json:"created_at"`
	EventType string `json:"event_type"`
	Filepath string `json:"filepath"`
	Fstat string `json:"fstat"`
	HostName string `json:"host_name"`
	KubernetesClusterId string `json:"kubernetes_cluster_id"`
	KubernetesClusterName string `json:"kubernetes_cluster_name"`
	Masked bool `json:"masked"`
	Netstat string `json:"netstat"`
	NodeId string `json:"node_id"`
	NodeType string `json:"node_type"`
	Pid int32 `json:"pid"`
	PodName string `json:"pod_name"`
	ProcStatus string `json:"proc_status"`
	ProcessName string `json:"process_name"`
	ResourceType string `json:"resource_type"`
	RuleId string `json:"rule_id"`
	Severity string `json:"severity"`
	SeverityScore float32 `json:"severity_score"`
	Summary string `json:"summary"`
	Tactics []string `json:"tactics"`
	Techniques []string `json:"techniques"`
	Top string `json:"top"`
	UpdatedAt int32 `json:"updated_at"`
	Users string `json:"users"`
	W int32 `json:"w"`
}

// NewModelFileAlert instantiates a new ModelFileAlert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelFileAlert(category string, containerId string, containerImage string, containerIp string, containerName string, count int32, createdAt int32, eventType string, filepath string, fstat string, hostName string, kubernetesClusterId string, kubernetesClusterName string, masked bool, netstat string, nodeId string, nodeType string, pid int32, podName string, procStatus string, processName string, resourceType string, ruleId string, severity string, severityScore float32, summary string, tactics []string, techniques []string, top string, updatedAt int32, users string, w int32) *ModelFileAlert {
	this := ModelFileAlert{}
	this.Category = category
	this.ContainerId = containerId
	this.ContainerImage = containerImage
	this.ContainerIp = containerIp
	this.ContainerName = containerName
	this.Count = count
	this.CreatedAt = createdAt
	this.EventType = eventType
	this.Filepath = filepath
	this.Fstat = fstat
	this.HostName = hostName
	this.KubernetesClusterId = kubernetesClusterId
	this.KubernetesClusterName = kubernetesClusterName
	this.Masked = masked
	this.Netstat = netstat
	this.NodeId = nodeId
	this.NodeType = nodeType
	this.Pid = pid
	this.PodName = podName
	this.ProcStatus = procStatus
	this.ProcessName = processName
	this.ResourceType = resourceType
	this.RuleId = ruleId
	this.Severity = severity
	this.SeverityScore = severityScore
	this.Summary = summary
	this.Tactics = tactics
	this.Techniques = techniques
	this.Top = top
	this.UpdatedAt = updatedAt
	this.Users = users
	this.W = w
	return &this
}

// NewModelFileAlertWithDefaults instantiates a new ModelFileAlert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelFileAlertWithDefaults() *ModelFileAlert {
	this := ModelFileAlert{}
	return &this
}

// GetCategory returns the Category field value
func (o *ModelFileAlert) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *ModelFileAlert) SetCategory(v string) {
	o.Category = v
}

// GetContainerId returns the ContainerId field value
func (o *ModelFileAlert) GetContainerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerId
}

// GetContainerIdOk returns a tuple with the ContainerId field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetContainerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerId, true
}

// SetContainerId sets field value
func (o *ModelFileAlert) SetContainerId(v string) {
	o.ContainerId = v
}

// GetContainerImage returns the ContainerImage field value
func (o *ModelFileAlert) GetContainerImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerImage
}

// GetContainerImageOk returns a tuple with the ContainerImage field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetContainerImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerImage, true
}

// SetContainerImage sets field value
func (o *ModelFileAlert) SetContainerImage(v string) {
	o.ContainerImage = v
}

// GetContainerIp returns the ContainerIp field value
func (o *ModelFileAlert) GetContainerIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerIp
}

// GetContainerIpOk returns a tuple with the ContainerIp field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetContainerIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerIp, true
}

// SetContainerIp sets field value
func (o *ModelFileAlert) SetContainerIp(v string) {
	o.ContainerIp = v
}

// GetContainerName returns the ContainerName field value
func (o *ModelFileAlert) GetContainerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerName
}

// GetContainerNameOk returns a tuple with the ContainerName field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerName, true
}

// SetContainerName sets field value
func (o *ModelFileAlert) SetContainerName(v string) {
	o.ContainerName = v
}

// GetCount returns the Count field value
func (o *ModelFileAlert) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ModelFileAlert) SetCount(v int32) {
	o.Count = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ModelFileAlert) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ModelFileAlert) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

// GetEventType returns the EventType field value
func (o *ModelFileAlert) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *ModelFileAlert) SetEventType(v string) {
	o.EventType = v
}

// GetFilepath returns the Filepath field value
func (o *ModelFileAlert) GetFilepath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filepath
}

// GetFilepathOk returns a tuple with the Filepath field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetFilepathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filepath, true
}

// SetFilepath sets field value
func (o *ModelFileAlert) SetFilepath(v string) {
	o.Filepath = v
}

// GetFstat returns the Fstat field value
func (o *ModelFileAlert) GetFstat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fstat
}

// GetFstatOk returns a tuple with the Fstat field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetFstatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fstat, true
}

// SetFstat sets field value
func (o *ModelFileAlert) SetFstat(v string) {
	o.Fstat = v
}

// GetHostName returns the HostName field value
func (o *ModelFileAlert) GetHostName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetHostNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostName, true
}

// SetHostName sets field value
func (o *ModelFileAlert) SetHostName(v string) {
	o.HostName = v
}

// GetKubernetesClusterId returns the KubernetesClusterId field value
func (o *ModelFileAlert) GetKubernetesClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubernetesClusterId
}

// GetKubernetesClusterIdOk returns a tuple with the KubernetesClusterId field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetKubernetesClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubernetesClusterId, true
}

// SetKubernetesClusterId sets field value
func (o *ModelFileAlert) SetKubernetesClusterId(v string) {
	o.KubernetesClusterId = v
}

// GetKubernetesClusterName returns the KubernetesClusterName field value
func (o *ModelFileAlert) GetKubernetesClusterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubernetesClusterName
}

// GetKubernetesClusterNameOk returns a tuple with the KubernetesClusterName field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetKubernetesClusterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubernetesClusterName, true
}

// SetKubernetesClusterName sets field value
func (o *ModelFileAlert) SetKubernetesClusterName(v string) {
	o.KubernetesClusterName = v
}

// GetMasked returns the Masked field value
func (o *ModelFileAlert) GetMasked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Masked
}

// GetMaskedOk returns a tuple with the Masked field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetMaskedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Masked, true
}

// SetMasked sets field value
func (o *ModelFileAlert) SetMasked(v bool) {
	o.Masked = v
}

// GetNetstat returns the Netstat field value
func (o *ModelFileAlert) GetNetstat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Netstat
}

// GetNetstatOk returns a tuple with the Netstat field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetNetstatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Netstat, true
}

// SetNetstat sets field value
func (o *ModelFileAlert) SetNetstat(v string) {
	o.Netstat = v
}

// GetNodeId returns the NodeId field value
func (o *ModelFileAlert) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ModelFileAlert) SetNodeId(v string) {
	o.NodeId = v
}

// GetNodeType returns the NodeType field value
func (o *ModelFileAlert) GetNodeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeType
}

// GetNodeTypeOk returns a tuple with the NodeType field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetNodeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeType, true
}

// SetNodeType sets field value
func (o *ModelFileAlert) SetNodeType(v string) {
	o.NodeType = v
}

// GetPid returns the Pid field value
func (o *ModelFileAlert) GetPid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pid
}

// GetPidOk returns a tuple with the Pid field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetPidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pid, true
}

// SetPid sets field value
func (o *ModelFileAlert) SetPid(v int32) {
	o.Pid = v
}

// GetPodName returns the PodName field value
func (o *ModelFileAlert) GetPodName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PodName
}

// GetPodNameOk returns a tuple with the PodName field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetPodNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PodName, true
}

// SetPodName sets field value
func (o *ModelFileAlert) SetPodName(v string) {
	o.PodName = v
}

// GetProcStatus returns the ProcStatus field value
func (o *ModelFileAlert) GetProcStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcStatus
}

// GetProcStatusOk returns a tuple with the ProcStatus field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetProcStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcStatus, true
}

// SetProcStatus sets field value
func (o *ModelFileAlert) SetProcStatus(v string) {
	o.ProcStatus = v
}

// GetProcessName returns the ProcessName field value
func (o *ModelFileAlert) GetProcessName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessName
}

// GetProcessNameOk returns a tuple with the ProcessName field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetProcessNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessName, true
}

// SetProcessName sets field value
func (o *ModelFileAlert) SetProcessName(v string) {
	o.ProcessName = v
}

// GetResourceType returns the ResourceType field value
func (o *ModelFileAlert) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ModelFileAlert) SetResourceType(v string) {
	o.ResourceType = v
}

// GetRuleId returns the RuleId field value
func (o *ModelFileAlert) GetRuleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetRuleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleId, true
}

// SetRuleId sets field value
func (o *ModelFileAlert) SetRuleId(v string) {
	o.RuleId = v
}

// GetSeverity returns the Severity field value
func (o *ModelFileAlert) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ModelFileAlert) SetSeverity(v string) {
	o.Severity = v
}

// GetSeverityScore returns the SeverityScore field value
func (o *ModelFileAlert) GetSeverityScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SeverityScore
}

// GetSeverityScoreOk returns a tuple with the SeverityScore field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetSeverityScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeverityScore, true
}

// SetSeverityScore sets field value
func (o *ModelFileAlert) SetSeverityScore(v float32) {
	o.SeverityScore = v
}

// GetSummary returns the Summary field value
func (o *ModelFileAlert) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *ModelFileAlert) SetSummary(v string) {
	o.Summary = v
}

// GetTactics returns the Tactics field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ModelFileAlert) GetTactics() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tactics
}

// GetTacticsOk returns a tuple with the Tactics field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelFileAlert) GetTacticsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tactics) {
		return nil, false
	}
	return o.Tactics, true
}

// SetTactics sets field value
func (o *ModelFileAlert) SetTactics(v []string) {
	o.Tactics = v
}

// GetTechniques returns the Techniques field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ModelFileAlert) GetTechniques() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Techniques
}

// GetTechniquesOk returns a tuple with the Techniques field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelFileAlert) GetTechniquesOk() ([]string, bool) {
	if o == nil || IsNil(o.Techniques) {
		return nil, false
	}
	return o.Techniques, true
}

// SetTechniques sets field value
func (o *ModelFileAlert) SetTechniques(v []string) {
	o.Techniques = v
}

// GetTop returns the Top field value
func (o *ModelFileAlert) GetTop() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Top
}

// GetTopOk returns a tuple with the Top field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetTopOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Top, true
}

// SetTop sets field value
func (o *ModelFileAlert) SetTop(v string) {
	o.Top = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ModelFileAlert) GetUpdatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetUpdatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ModelFileAlert) SetUpdatedAt(v int32) {
	o.UpdatedAt = v
}

// GetUsers returns the Users field value
func (o *ModelFileAlert) GetUsers() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetUsersOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Users, true
}

// SetUsers sets field value
func (o *ModelFileAlert) SetUsers(v string) {
	o.Users = v
}

// GetW returns the W field value
func (o *ModelFileAlert) GetW() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.W
}

// GetWOk returns a tuple with the W field value
// and a boolean to check if the value has been set.
func (o *ModelFileAlert) GetWOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.W, true
}

// SetW sets field value
func (o *ModelFileAlert) SetW(v int32) {
	o.W = v
}

func (o ModelFileAlert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelFileAlert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category"] = o.Category
	toSerialize["container_id"] = o.ContainerId
	toSerialize["container_image"] = o.ContainerImage
	toSerialize["container_ip"] = o.ContainerIp
	toSerialize["container_name"] = o.ContainerName
	toSerialize["count"] = o.Count
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["event_type"] = o.EventType
	toSerialize["filepath"] = o.Filepath
	toSerialize["fstat"] = o.Fstat
	toSerialize["host_name"] = o.HostName
	toSerialize["kubernetes_cluster_id"] = o.KubernetesClusterId
	toSerialize["kubernetes_cluster_name"] = o.KubernetesClusterName
	toSerialize["masked"] = o.Masked
	toSerialize["netstat"] = o.Netstat
	toSerialize["node_id"] = o.NodeId
	toSerialize["node_type"] = o.NodeType
	toSerialize["pid"] = o.Pid
	toSerialize["pod_name"] = o.PodName
	toSerialize["proc_status"] = o.ProcStatus
	toSerialize["process_name"] = o.ProcessName
	toSerialize["resource_type"] = o.ResourceType
	toSerialize["rule_id"] = o.RuleId
	toSerialize["severity"] = o.Severity
	toSerialize["severity_score"] = o.SeverityScore
	toSerialize["summary"] = o.Summary
	if o.Tactics != nil {
		toSerialize["tactics"] = o.Tactics
	}
	if o.Techniques != nil {
		toSerialize["techniques"] = o.Techniques
	}
	toSerialize["top"] = o.Top
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["users"] = o.Users
	toSerialize["w"] = o.W
	return toSerialize, nil
}

type NullableModelFileAlert struct {
	value *ModelFileAlert
	isSet bool
}

func (v NullableModelFileAlert) Get() *ModelFileAlert {
	return v.value
}

func (v *NullableModelFileAlert) Set(val *ModelFileAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableModelFileAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableModelFileAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelFileAlert(val *ModelFileAlert) *NullableModelFileAlert {
	return &NullableModelFileAlert{value: val, isSet: true}
}

func (v NullableModelFileAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelFileAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


