/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v2.3.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelAttachAgentConfigReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAttachAgentConfigReq{}

// ModelAttachAgentConfigReq struct for ModelAttachAgentConfigReq
type ModelAttachAgentConfigReq struct {
	AgentIds []ModelAgentID `json:"agent_ids"`
	ConfigId string `json:"config_id"`
}

type _ModelAttachAgentConfigReq ModelAttachAgentConfigReq

// NewModelAttachAgentConfigReq instantiates a new ModelAttachAgentConfigReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAttachAgentConfigReq(agentIds []ModelAgentID, configId string) *ModelAttachAgentConfigReq {
	this := ModelAttachAgentConfigReq{}
	this.AgentIds = agentIds
	this.ConfigId = configId
	return &this
}

// NewModelAttachAgentConfigReqWithDefaults instantiates a new ModelAttachAgentConfigReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAttachAgentConfigReqWithDefaults() *ModelAttachAgentConfigReq {
	this := ModelAttachAgentConfigReq{}
	return &this
}

// GetAgentIds returns the AgentIds field value
// If the value is explicit nil, the zero value for []ModelAgentID will be returned
func (o *ModelAttachAgentConfigReq) GetAgentIds() []ModelAgentID {
	if o == nil {
		var ret []ModelAgentID
		return ret
	}

	return o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelAttachAgentConfigReq) GetAgentIdsOk() ([]ModelAgentID, bool) {
	if o == nil || IsNil(o.AgentIds) {
		return nil, false
	}
	return o.AgentIds, true
}

// SetAgentIds sets field value
func (o *ModelAttachAgentConfigReq) SetAgentIds(v []ModelAgentID) {
	o.AgentIds = v
}

// GetConfigId returns the ConfigId field value
func (o *ModelAttachAgentConfigReq) GetConfigId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfigId
}

// GetConfigIdOk returns a tuple with the ConfigId field value
// and a boolean to check if the value has been set.
func (o *ModelAttachAgentConfigReq) GetConfigIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigId, true
}

// SetConfigId sets field value
func (o *ModelAttachAgentConfigReq) SetConfigId(v string) {
	o.ConfigId = v
}

func (o ModelAttachAgentConfigReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAttachAgentConfigReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AgentIds != nil {
		toSerialize["agent_ids"] = o.AgentIds
	}
	toSerialize["config_id"] = o.ConfigId
	return toSerialize, nil
}

func (o *ModelAttachAgentConfigReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_ids",
		"config_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelAttachAgentConfigReq := _ModelAttachAgentConfigReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelAttachAgentConfigReq)

	if err != nil {
		return err
	}

	*o = ModelAttachAgentConfigReq(varModelAttachAgentConfigReq)

	return err
}

type NullableModelAttachAgentConfigReq struct {
	value *ModelAttachAgentConfigReq
	isSet bool
}

func (v NullableModelAttachAgentConfigReq) Get() *ModelAttachAgentConfigReq {
	return v.value
}

func (v *NullableModelAttachAgentConfigReq) Set(val *ModelAttachAgentConfigReq) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAttachAgentConfigReq) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAttachAgentConfigReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAttachAgentConfigReq(val *ModelAttachAgentConfigReq) *NullableModelAttachAgentConfigReq {
	return &NullableModelAttachAgentConfigReq{value: val, isSet: true}
}

func (v NullableModelAttachAgentConfigReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAttachAgentConfigReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


