/*
Deepfence ThreatStryker

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v2.5.2
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelAPIEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIEndpoint{}

// ModelAPIEndpoint struct for ModelAPIEndpoint
type ModelAPIEndpoint struct {
	CloudProvider *string `json:"cloud_provider,omitempty"`
	CloudRegion *string `json:"cloud_region,omitempty"`
	CloudType *string `json:"cloud_type,omitempty"`
	CreatedAt *int32 `json:"created_at,omitempty"`
	Direction *string `json:"direction,omitempty"`
	Host *string `json:"host,omitempty"`
	HostIp *string `json:"host_ip,omitempty"`
	Method *string `json:"method,omitempty"`
	Path *string `json:"path,omitempty"`
	Port *int32 `json:"port,omitempty"`
	SchemaInfo *string `json:"schema_info,omitempty"`
	SourceHosts []string `json:"source_hosts,omitempty"`
	UpdatedAt *int32 `json:"updated_at,omitempty"`
}

// NewModelAPIEndpoint instantiates a new ModelAPIEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIEndpoint() *ModelAPIEndpoint {
	this := ModelAPIEndpoint{}
	return &this
}

// NewModelAPIEndpointWithDefaults instantiates a new ModelAPIEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIEndpointWithDefaults() *ModelAPIEndpoint {
	this := ModelAPIEndpoint{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetCloudProvider() string {
	if o == nil || IsNil(o.CloudProvider) {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetCloudProviderOk() (*string, bool) {
	if o == nil || IsNil(o.CloudProvider) {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasCloudProvider() bool {
	if o != nil && !IsNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *ModelAPIEndpoint) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCloudRegion returns the CloudRegion field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetCloudRegion() string {
	if o == nil || IsNil(o.CloudRegion) {
		var ret string
		return ret
	}
	return *o.CloudRegion
}

// GetCloudRegionOk returns a tuple with the CloudRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetCloudRegionOk() (*string, bool) {
	if o == nil || IsNil(o.CloudRegion) {
		return nil, false
	}
	return o.CloudRegion, true
}

// HasCloudRegion returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasCloudRegion() bool {
	if o != nil && !IsNil(o.CloudRegion) {
		return true
	}

	return false
}

// SetCloudRegion gets a reference to the given string and assigns it to the CloudRegion field.
func (o *ModelAPIEndpoint) SetCloudRegion(v string) {
	o.CloudRegion = &v
}

// GetCloudType returns the CloudType field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetCloudType() string {
	if o == nil || IsNil(o.CloudType) {
		var ret string
		return ret
	}
	return *o.CloudType
}

// GetCloudTypeOk returns a tuple with the CloudType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetCloudTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CloudType) {
		return nil, false
	}
	return o.CloudType, true
}

// HasCloudType returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasCloudType() bool {
	if o != nil && !IsNil(o.CloudType) {
		return true
	}

	return false
}

// SetCloudType gets a reference to the given string and assigns it to the CloudType field.
func (o *ModelAPIEndpoint) SetCloudType(v string) {
	o.CloudType = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetCreatedAt() int32 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetCreatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *ModelAPIEndpoint) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *ModelAPIEndpoint) SetDirection(v string) {
	o.Direction = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *ModelAPIEndpoint) SetHost(v string) {
	o.Host = &v
}

// GetHostIp returns the HostIp field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetHostIp() string {
	if o == nil || IsNil(o.HostIp) {
		var ret string
		return ret
	}
	return *o.HostIp
}

// GetHostIpOk returns a tuple with the HostIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetHostIpOk() (*string, bool) {
	if o == nil || IsNil(o.HostIp) {
		return nil, false
	}
	return o.HostIp, true
}

// HasHostIp returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasHostIp() bool {
	if o != nil && !IsNil(o.HostIp) {
		return true
	}

	return false
}

// SetHostIp gets a reference to the given string and assigns it to the HostIp field.
func (o *ModelAPIEndpoint) SetHostIp(v string) {
	o.HostIp = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *ModelAPIEndpoint) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ModelAPIEndpoint) SetPath(v string) {
	o.Path = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *ModelAPIEndpoint) SetPort(v int32) {
	o.Port = &v
}

// GetSchemaInfo returns the SchemaInfo field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetSchemaInfo() string {
	if o == nil || IsNil(o.SchemaInfo) {
		var ret string
		return ret
	}
	return *o.SchemaInfo
}

// GetSchemaInfoOk returns a tuple with the SchemaInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetSchemaInfoOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaInfo) {
		return nil, false
	}
	return o.SchemaInfo, true
}

// HasSchemaInfo returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasSchemaInfo() bool {
	if o != nil && !IsNil(o.SchemaInfo) {
		return true
	}

	return false
}

// SetSchemaInfo gets a reference to the given string and assigns it to the SchemaInfo field.
func (o *ModelAPIEndpoint) SetSchemaInfo(v string) {
	o.SchemaInfo = &v
}

// GetSourceHosts returns the SourceHosts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelAPIEndpoint) GetSourceHosts() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SourceHosts
}

// GetSourceHostsOk returns a tuple with the SourceHosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelAPIEndpoint) GetSourceHostsOk() ([]string, bool) {
	if o == nil || IsNil(o.SourceHosts) {
		return nil, false
	}
	return o.SourceHosts, true
}

// HasSourceHosts returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasSourceHosts() bool {
	if o != nil && !IsNil(o.SourceHosts) {
		return true
	}

	return false
}

// SetSourceHosts gets a reference to the given []string and assigns it to the SourceHosts field.
func (o *ModelAPIEndpoint) SetSourceHosts(v []string) {
	o.SourceHosts = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelAPIEndpoint) GetUpdatedAt() int32 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int32
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIEndpoint) GetUpdatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelAPIEndpoint) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int32 and assigns it to the UpdatedAt field.
func (o *ModelAPIEndpoint) SetUpdatedAt(v int32) {
	o.UpdatedAt = &v
}

func (o ModelAPIEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CloudProvider) {
		toSerialize["cloud_provider"] = o.CloudProvider
	}
	if !IsNil(o.CloudRegion) {
		toSerialize["cloud_region"] = o.CloudRegion
	}
	if !IsNil(o.CloudType) {
		toSerialize["cloud_type"] = o.CloudType
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.HostIp) {
		toSerialize["host_ip"] = o.HostIp
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.SchemaInfo) {
		toSerialize["schema_info"] = o.SchemaInfo
	}
	if o.SourceHosts != nil {
		toSerialize["source_hosts"] = o.SourceHosts
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableModelAPIEndpoint struct {
	value *ModelAPIEndpoint
	isSet bool
}

func (v NullableModelAPIEndpoint) Get() *ModelAPIEndpoint {
	return v.value
}

func (v *NullableModelAPIEndpoint) Set(val *ModelAPIEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIEndpoint(val *ModelAPIEndpoint) *NullableModelAPIEndpoint {
	return &NullableModelAPIEndpoint{value: val, isSet: true}
}

func (v NullableModelAPIEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


