/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelEnableFilesystemTracerReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelEnableFilesystemTracerReq{}

// ModelEnableFilesystemTracerReq struct for ModelEnableFilesystemTracerReq
type ModelEnableFilesystemTracerReq struct {
	AgentIds []ModelAgentId `json:"agent_ids"`
	Path string `json:"path"`
}

// NewModelEnableFilesystemTracerReq instantiates a new ModelEnableFilesystemTracerReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelEnableFilesystemTracerReq(agentIds []ModelAgentId, path string) *ModelEnableFilesystemTracerReq {
	this := ModelEnableFilesystemTracerReq{}
	this.AgentIds = agentIds
	this.Path = path
	return &this
}

// NewModelEnableFilesystemTracerReqWithDefaults instantiates a new ModelEnableFilesystemTracerReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelEnableFilesystemTracerReqWithDefaults() *ModelEnableFilesystemTracerReq {
	this := ModelEnableFilesystemTracerReq{}
	return &this
}

// GetAgentIds returns the AgentIds field value
// If the value is explicit nil, the zero value for []ModelAgentId will be returned
func (o *ModelEnableFilesystemTracerReq) GetAgentIds() []ModelAgentId {
	if o == nil {
		var ret []ModelAgentId
		return ret
	}

	return o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelEnableFilesystemTracerReq) GetAgentIdsOk() ([]ModelAgentId, bool) {
	if o == nil || IsNil(o.AgentIds) {
		return nil, false
	}
	return o.AgentIds, true
}

// SetAgentIds sets field value
func (o *ModelEnableFilesystemTracerReq) SetAgentIds(v []ModelAgentId) {
	o.AgentIds = v
}

// GetPath returns the Path field value
func (o *ModelEnableFilesystemTracerReq) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ModelEnableFilesystemTracerReq) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ModelEnableFilesystemTracerReq) SetPath(v string) {
	o.Path = v
}

func (o ModelEnableFilesystemTracerReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelEnableFilesystemTracerReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AgentIds != nil {
		toSerialize["agent_ids"] = o.AgentIds
	}
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

type NullableModelEnableFilesystemTracerReq struct {
	value *ModelEnableFilesystemTracerReq
	isSet bool
}

func (v NullableModelEnableFilesystemTracerReq) Get() *ModelEnableFilesystemTracerReq {
	return v.value
}

func (v *NullableModelEnableFilesystemTracerReq) Set(val *ModelEnableFilesystemTracerReq) {
	v.value = val
	v.isSet = true
}

func (v NullableModelEnableFilesystemTracerReq) IsSet() bool {
	return v.isSet
}

func (v *NullableModelEnableFilesystemTracerReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelEnableFilesystemTracerReq(val *ModelEnableFilesystemTracerReq) *NullableModelEnableFilesystemTracerReq {
	return &NullableModelEnableFilesystemTracerReq{value: val, isSet: true}
}

func (v NullableModelEnableFilesystemTracerReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelEnableFilesystemTracerReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


